/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/uCQSUEJMmbR
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
  CardTitle,
  CardDescription,
  CardContent,
  Card,
} from "@/components/ui/card";
type CardUIProps = {
  number: number;
  title: string;
  description: string;
};
export default function CardUI({ number, title, description }: CardUIProps) {
  return (
    <div className=" flex items-center justify-center">
      <Card className="w-full max-w-sm rounded-lg shadow-md h-[80vh] ">
        <div className="h-[50vh] text-8xl flex items-center justify-center">
          {number}
        </div>
        <CardContent className="p-5">
          <CardTitle className="text-2xl font-bold mb-2">{title}</CardTitle>
          <CardDescription className="text-gray-500">
            {description}
          </CardDescription>
        </CardContent>
      </Card>
    </div>
  );
}
